version: "3.9"

services:
  bankaccounts-api:
    build:
      context: .
      dockerfile: BankAccounts/Dockerfile
    container_name: bankaccounts-api
    ports:
      - "80:80"
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=db;Username=admin;Password=admin
    depends_on:
      - keycloak
      - postgres
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    ports:
      - "8081:8080" 
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
